### ISSUE TITLE
Commiters are not valid reviewers

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#3]
It's currently possible for a PR author to list herself as a reviewer. The PR author should not be a valid reviewer for a PR.

We should either filter out the author silently from the reviewers list or raise a different error if we encounter the PR author in the reviewers list. Open to discussion on which is the best course.

**Comment by robertmonahon** [comment]
Should it be PR author that is restricted or the author of the commits in the PR?  I'm imagining a scenario where I'm propagating someone's code because they're out, in a different time zone, etc. so I should be able to review it even though I've created the PR.

I'm in favor of silently ignoring because we already have an error for not enough code reviewers, right? No need to throw an extra error in my opinion.

**Comment by aergonaut** [comment]
For this one, I initially had the same intuition, but now I'm actually leaning towards raising a new error.

If they list 2 people (one being themselves), and we come back saying there's not enough reviewers, it's not immediately obvious that what's wrong is that they've listed themselves and they can't do that. But if we raise a different error, then it's clear what needs to be fixed about the reviewers list. :information_desk_person:

**Comment by robertmonahon** [comment]
But anyone who can't figure out "oh, maybe I'm not allowed to review my own thing" .... :stare: :grumpycat:

**Comment by aergonaut** [comment]
Fixed in #499
