### ISSUE TITLE
add label "Review Complete" to PR

### ISSUE THREAD

**Issue by mekhovov** [aergonaut/cody#5]
that would be nice to put the label `Review Complete` automatically to the PR if review done.

this label is on the top of PR because of that it's visible and you shouldn't scroll down to the bottom to see is is done :)

<img width="1020" alt="screenshot 2016-01-05 20 54 33" src="https://cloud.githubusercontent.com/assets/194539/12125976/dc7f0fc4-b3ee-11e5-9e02-fe0b1c5bbd60.png">

@aergonaut make sense? :)

**Comment by aergonaut** [comment]
I'm not sure if I like this one. Since the code review progress is already reported at the bottom of the Pull Request, I don't like duplicating the information with a label.

Internally, we had been using labels basically for the same purpose as commit statuses. Now that we have services that properly integrate with commit statuses, I think we should stick with commit statuses. They're built just for this job of reporting information about a PR from external services.
