### ISSUE TITLE
Automatically add risk level tag

### ISSUE THREAD

**Issue by zrandles** [aergonaut/cody#8]
Cody should require more reviewers for more complex PRs. One way to indicate that a PR requires more attention is by adding a risk level. Unfortunately most people aren't very good about adding their own, so let's have Cody do it for them.

Some signals to use:
- Number of lines added/deleted
- Number of files touched
- Migration added?

This could happen upon PR creation or each time a comment is added (since we already trigger other things on those events). Better would be to trigger each time a commit is made.

We should leave the option of manually increasing the risk level, so Cody should only add labels that are higher than the existing label. Also need to remove existing labels so we don't end up with a ticket tagged risk level 1, 2, and 3.

Other signals could be used for this or other purposes, but I'll leave those for their own issue.

**Comment by aergonaut** [comment]
I don't really like this specific idea because the concept of risk level labels is too specific to our own workflow. I'd rather focus on the list of reviewers and manipulating that, as opposed to something tangential to the code review (albeit related).

I like the general idea of this, and I think it plays into wanting Cody to be able to enforce particular review processes in response to certain triggers or characteristics in the PR. Size of the diff, names of files in the diff, etc.

In our case, adding the risk level labels always coincides with adding one or more extra reviewers, based on the reason for the escalation in risk. If we build that into Cody, I think we should focus on making a system where we can specify the rules that cause those extra reviewers to be added, rather than focusing on the labels.

Before we can tackle this, though, we'll need to figure out a way to let Cody update the PR description. I think this should be possible and relatively easy, but if Cody is going to be adding more reviewers to the list automatically, he needs to be able to report that.
